# Generated by Django 5.1.6 on 2025-03-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
