# Generated by Django 5.1.6 on 2025-03-28 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_task_priority_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='editors',
            field=models.ManyToManyField(related_name='boards', to='models.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='models.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('TD', 'Completed'), ('AN', 'Assistance Needed')], default='NS', max_length=2),
        ),
    ]
