# Generated by Django 5.1.6 on 2025-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_cookie_user_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
